# Generated by Django 3.0.5 on 2022-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_appointment_pre_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/images/error.jpg', null=True, upload_to='profile_pic/DoctorProfilePic/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/images/error.jpg', null=True, upload_to='profile_pic/PatientProfilePic/'),
        ),
    ]
