# Generated by Django 3.0.5 on 2022-04-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0022_auto_20220417_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('General Practitioner', 'General Practitioner'), ('Physiotherapist', 'Physiotherapist'), ('Dentist', 'Dentist'), ('Pediatrician', 'Pediatrician'), ('Orthopedist', 'Orthopedist')], default='Cardiologist', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(default='NA', max_length=100, null=True),
        ),
    ]
